<?php
//for query
// require_once(file_location('inc_path','connection.inc.php'));
// @$conn = dbconnect('admin','PDO');
// $sql = "SELECT project_table.p_id AS id, p_type, p_name, p_link, p_color, p_languages, p_info, 
// 		CONCAT(pm_link_name, '.' , pm_extension) projectImg
// 		FROM project_table,project_media_table
// 		WHERE project_table.p_id= project_media_table.p_id 
// 		ORDER BY p_rank, project_table.p_id DESC";
// $stmt = $conn->prepare($sql);
// $stmt->execute();
// $stmt->setFetchMode(PDO::FETCH_OBJ);
// echo json_encode(($stmt->fetchAll()));

$data = [
    ["id" => "5","p_type" => "web","p_name" => "Single Vendor-Multi Product Ecommerce Web App","p_link" => "https:\/\/mystoremrkt.000webhostapp.com","p_rank" => 1,"p_color" => "black","p_languages" => "HTML, CSS, JavaScript, Jquery, PHP, MySql, AJAX, JSON and XML","p_info" => "This project renders an Ecommerce web app which features multi-products run by a single vendor.\r\nIt features include:\r\n- Admin section with different admin level\r\n- User section with login and registration features\r\n- Cart and checkout\r\n- Tracking of order status\r\n- Online payment with payment gateway\r\n- Option of making payment when order is delivered or picked up\r\n- Pickup and home delivery options\r\n- Print receipt\r\n- All transactions and it yearly, monthly, daily data\r\n- Many more features","projectImg" => "mystore.jpg"],
    ["id" => "4","p_type" => "web","p_name" => "Real Estate Website","p_link" => "https:\/\/jephrealestate.000webhostapp.com","p_rank" => 1,"p_color" => "black","p_languages" => "HTML, CSS, JavaScript, Jquery, PHP, MySql, AJAX, JSON and XML","p_info" => "This project approaches the problem of finding a real estate property within a locality through a certain real estate management firm.\r\nIt features include:\r\n- Admin section with different admin level\r\n- Uploading new, editing and deleting property at the admin section\r\n- Browsing new property by user\r\n- Users can make appointment on property that entice them\r\n- Blog section\r\n- Comment can be added on blog\r\n- Articles can be shared on other platform with just a click\r\n- Many more features","projectImg" => "realestate.jpg"],
    ["id" => "6","p_type" => "web","p_name" => "Logistics Landing Page","p_link" => "https:\/\/smartmovelog.000webhostapp.com","p_rank" => 2,"p_color" => "black","p_languages" => "HTML, CSS, JavaScript, Jquery, PHP, AJAX, JSON and XML","p_info" => "A 6 pages websites which focus on Logistics.\r\nIt features include:\r\n- Landing Page\r\n- Whatsapp Connect and Call Buttons\r\n- Contact Us, FAQ, Policy Privacy and co Pages\r\n- Social Handles Connects\r\n- Social Handles Connects\r\n- Many more features","projectImg" => "smartmovelog.jpg"],
    ["id" => "3","p_type" => "web","p_name" => "Single Vendor Food Ordering Web App","p_link" => "https:\/\/eatwellre.000webhostapp.com","p_rank" => 2,"p_color" => "black","p_languages" => "HTML, CSS, JavaScript, Jquery, PHP, MySql, AJAX, JSON and XML","p_info" => "This project renders an food ordering and delivery web app run by a single vendor.\r\nIt features include:\r\n- Admin section with different admin level\r\n- User section with login and registration features\r\n- Cart and checkout\r\n- Tracking of order status\r\n- Online payment with payment gateway\r\n- Option of making payment when order is delivered or picked up\r\n- Pickup and home delivery options\r\n- Print receipt\r\n- All transactions and it yearly, monthly, daily data\r\n- Many more features","projectImg" => "eatwell.jpg"],
    ["id" => "7","p_type" => "web","p_name" => "ClearLink Landing Page","p_link" => "https:\/\/jephthiano-clearlink.vercel.app","p_rank" => 2,"p_color" => "black","p_languages" => "HTML, CSS, JavaScript, React JS","p_info" => "A 6 pages websites which focus on Logistics.\r\nIt features include:\r\n- Landing Page\r\n- Icons \r\n- Responsiveness\r\n- Social Handles Connects\r\n- Many more features","projectImg" => "clearlink.jpg"],
    ["id" => "8","p_type" => "web","p_name" => "Dashboard Page","p_link" => "https:\/\/jeph-dashboar.vercel.app","p_rank" => 2,"p_color" => "black","p_languages" => "HTML, CSS, JavaScript, React JS","p_info" => "A single page admin dashboard.\r\nIt features include:\r\n- Dashboard Page\r\n- Chart and Icons\r\n- Responsiveness\r\n- Many more features","projectImg" => "dashboard.jpg"],
    ["id" => "2","p_type" => "web","p_name" => "Foundation\/Charity Website","p_link" => "https:\/\/jephdation.000webhostapp.com","p_rank" => 3,"p_color" => "black","p_languages" => "HTML, CSS, JavaScript, Jquery, PHP, MySql, AJAX, JSON and XML","p_info" => "This project is based on foundation website. and it can be run by charity\/foundation organization.\r\nIt features include:\r\n- Admin section with different admin level\r\n- Admin controls everything from the admin section\r\n- Option for donation with payment gateway\r\n- News and progarmmes section for users\r\n- Users can comment on each news\r\n- Users can share news with one click\r\n- Many more features","projectImg" => "foundation.jpg"],
    ["id" => "1","p_type" => "web","p_name" => "Blog\/News Website","p_link" => "https:\/\/jobsblog333.000webhostapp.com","p_rank" => 3,"p_color" => "black","p_languages" => "HTML, CSS, JavaScript, Jquery, PHP, MySql, AJAX, JSON and XML","p_info" => "This project is based on blog\/news website.\r\nIt features include:\r\n- Admin section with different admin level\r\n- Admin controls everything from the admin section\r\n- Users read news\r\n- Users can comment on each news\r\n- Users can share news with one click\r\n- Many more features","projectImg" => "blog.jpg"]
];

$result = json_encode($data);
echo ($result);